### ISSUE TITLE
Add the number layout

### ISSUE THREAD

**Issue by supersharpbk** [JsonSchema-JavaUI/sf-java-ui#17]
### Description

Add the number layout

### Modifications

1. Add new @Number annotation with appropriate fields
2. Implement the NumberGenerator
3. Improve the demo app to support the number layout

**Expected behavior:** Support the number layout

**Comment by supersharpbk** [comment]
Title problem

**Comment by SaifJerbi** [comment]
@ahdbk problem resolved in fix in commit 184f751
