### ISSUE TITLE
Add the datepicker layout

### ISSUE THREAD

**Issue by Z7oussem** [JsonSchema-JavaUI/sf-java-ui#34]
### Description

Add the datepicker layout

### Modifications

1. Add new @DatePicker annotation
2. Implement the DatePickerGenerator
3. Improve the demo app to support the datepicker layout
4. Add the datepicker add on

**Expected behavior:** Support the datepicker layout

**Comment by SaifJerbi** [comment]
It's fixed by adding new external project https://github.com/JsonSchema-JavaUI/sf-java-ui-addons
Implementing a mechanism to support external librairy addons
