### ISSUE TITLE
Add fieldAddon support to Number , Password, TextArea and TextField

### ISSUE THREAD

**Issue by supersharpbk** [JsonSchema-JavaUI/sf-java-ui#45]
### Description

Add fieldAddon support to Number , Password , TextField and  Text Area #3 
- Add fieldAddonRight ----@
- Add fieldAddonLeft @----

**Expected behavior:** - fieldAddon support

**Actual behavior:** fieldAddon not supported

**Comment by SaifJerbi** [comment]
@ahdbk should we close this issue? or not yet completed

**Comment by supersharpbk** [comment]
I edited the issue to support TextArea too . I will close it in the next pull request
