### ISSUE TITLE
Add radio layout support

### ISSUE THREAD

**Issue by SaifJerbi** [JsonSchema-JavaUI/sf-java-ui#5]
In order to support this new layout we have to : 
- Add new @RadioBox annotation with appropriate fields
- Implement the RadioBoxGenerator
- Improve the demo app to support the radioBox layout

**Comment by DhiaEddineSaidi** [comment]
Please asseign me this ticket

**Comment by SaifJerbi** [comment]
Issue assigned to @DhiaEddineSaidi
