### ISSUE TITLE
JSON generated from TitleMap is Invalid

### ISSUE THREAD

**Issue by lbispham** [JsonSchema-JavaUI/sf-java-ui#79]
### Description

I am generating a RadioBox from a TitleMap. The form JSON is invalid.

### Steps to Reproduce

1. 
public class UserValues implements ValuesContainer {

    @Override
    public Map<String, String> getValues() {
        ImmutableMap.Builder<String, String> builder = ImmutableMap.builder();
        builder.put("Custom", "Custom");
        builder.put("Standard", "Standard");
        return builder.build();
    }
}

2. 
@RadioBox(title = "Choose a setting", titleMap =  UserValues .class)
private String choose;

**Expected behavior:** [What you expect to happen]

I expect my JSON for the form to look like this:

`{
            "key": "choose",
            "readOnly": false,
            "type": "radios",
            "titleMap": [
              {
                "name": "Custom",
                "value": "Custom"
              },
              {
                "name": "Standard",
                "value": "Standard"
              }
            ]
          }`

**Actual behavior:** [What actually happens]

Instead the JSON is invalid and looks like this (no quotation marks around the values in the titleMap):

`{
            "key": "choose",
            "readOnly": false,
            "type": "radios",
            "titleMap": [
              {
                "name": "Custom",
                "value": Custom
              },
              {
                "name": "Standard",
                "value": Standard
              }
            ]
          }`

### Versions
1.0.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by SaifJerbi** [comment]
Hi @lbispham,

I can't reproduce the issue. I used the same implementation but the issue is not reproduced.
```java
// My field
@RadioBox(title="Gender", titleMap=GenderTitleMap.class)
private String gender;
```

```java

// My Map values
@Override
public Map<String, String> getValues() {
	ImmutableMap.Builder<String, String> builder = ImmutableMap.builder();
	builder.put("Male", "Male");
	builder.put("Female", "Female");
	return builder.build();
}
```

I got the json below:
```json
// The result
[
  {
    "key": "gender",
    "readOnly": false,
    "type": "radios",
    "titleMap": [
      {
        "name": "Male",
        "value": "Male"
      },
      {
        "name": "Female",
        "value": "Female"
      }
    ]
  }
]
```

Can you please try to use the [demo app](https://github.com/JsonSchema-JavaUI/sf-java-ui/tree/master/demo) and try to reproduce your issue or fill more details about your app environment
